{f:cachemenustart}
<br>
<a class={get:render;"ctmp1_class"} href={b:link_std}/cache_test.html>Cache Test Main</a>
{if:is_ssl_available}
<a class={get:render;"ctmp11_class"} href={b:link_ssl}/cache_test.html>SSL</a>
{endif}
<a class={get:render;"ctmp2_class"} href={b:link_std}/cache_test1.html>Cache Test 1</a> 
{if:is_ssl_available}
<a class={get:render;"ctmp22_class"} href={b:link_ssl}/cache_test1.html>SSL</a>
{endif}
<a class={get:render;"ctmp3_class"} href={b:link_std}/cache_test2.html>Cache Test 2</a> 
{if:is_ssl_available}
<a class={get:render;"ctmp33_class"} href={b:link_ssl}/cache_test2.html>SSL</a>
{endif}
<a class={get:render;"ctmp4_class"} href={b:link_std}/cache_test3.html>Cache Test 3</a> 
{if:is_ssl_available}
<a class={get:render;"ctmp44_class"} href={b:link_ssl}/cache_test3.html>SSL</a>
{endif}
<a class={get:render;"ctmp5_class"} href={b:link_std}/cache_test4.html>Cache Test 4</a> 
{if:is_ssl_available}
<a class={get:render;"ctmp55_class"} href={b:link_ssl}/cache_test4.html>SSL</a>
{endif}
<a class={get:render;"ctmp6_class"} href={b:link_std}/cache_test_alle.html>Cache Test Alle</a> 
{if:is_ssl_available}
<a class={get:render;"ctmp66_class"} href={b:link_ssl}/cache_test_alle.html>SSL</a>
{endif}
<br> 