
OPTS= -DLINUX
#-O2

FLAGS=-I../../lib/ -I../../lib/include/ -I../../lib/include/intern/ -I../../lib/third_party/src/simclist/ -I../../lib/third_party/src/rb_tree/ \
	-I../../lib/platform/include/ ${OPTS}

FILES=../../lib/src/convert.c
 # -fsanitize=address

include ../Makefile.afl_inc

	


