
AFL=../../afl-2.10b

all: main.gcc main.afl.clang

clean:
	rm -f main.gcc main.afl.clang

CLANG_FLAGS= -fno-omit-frame-pointer  ${FLAGS}

LIBS=-lc -lssl -lcrypto -ldl -lpthread -levent -levent_pthreads

main.gcc: ${FILES} main.c
	gcc ${FLAGS} main.c ${FILES} -o main.gcc ${LIBS}

main.afl.clang: ${FILES} main.c
	$(AFL)/afl-clang-fast -DAFL_PER -O2 ${CLANG_FLAGS}  main.c ${FILES} -o main.afl.clang -lc -lssl -lcrypto -ldl -lpthread -levent -levent_pthreads



run:
	$(AFL)/afl-fuzz -M fuzzer01 -i input -o output -- $$(pwd)/main.afl.clang

run_slave1:
	$(AFL)/afl-fuzz -S fuzzer02 -i input -o output -- $$(pwd)/main.afl.clang

run_slave2:
	$(AFL)/afl-fuzz -S fuzzer03 -i input -o output -- $$(pwd)/main.afl.clang

run_slave3:
	$(AFL)/afl-fuzz -S fuzzer04 -i input -o output -- $$(pwd)/main.afl.clang




# scan-build make static_analyse
static_analyse: 
	clang ${CLANG_FLAGS} -Os main.c ${FILES}  -o main.clang ${LIBS}

lto:
	clang ${CLANG_FLAGS} -flto -O3 main.c ${FILES}  -o main.clang.lto ${LIBS}
	gcc ${FLAGS} -flto -Os main.c ${FILES}  -o main.gcc.lto ${LIBS}
	
	clang ${CLANG_FLAGS} -Os main.c ${FILES}  -o main.clang ${LIBS}
	gcc ${FLAGS} -Os main.c ${FILES}  -o main.gcc ${LIBS}
