language: c

env:
  global:
    secure: "SS5efj7kz0thoFmWqwrLwvXVvMMviJ2tKk+y0E6FyiVXZ173qRPn5ZGlIpLVVwx0pev1tf92+RQ/BmTha3lREf+qc9Gt9G3lBXzch4m5+gKAOG2XWvqSKnD2nVGBVjZvvC579Bt1JhFJ1bKMETGdJGOOCNU2+1TQlCfFhOPMCuORBD5m1N2kDWhGoDr8jhoV884gFeLYvSoQLbrXLo9IXVsj+KWI97Ck8SMCtT3oPc7jtqQrsZ4ECS5N+wXvR71HPpgP1lIe/K/wvvkLQmZvVWnVsroiiwGQbWKJuN0CcbG2ooxkzYT4BMbCoVdyezxFZNkyMQB7Adzgera+Cymh0zmQadK4SYuPR6wl+K9K8wgfGDikAw0dUyVnI2JjDvGjRq9IFy8nUfOK70OSP2OLG0FsSLCYENkm5+/iek41gEd7W0A7Kfz6n+4djGguqML8TJaKMY2qQ2so/hyE1Pv2ne2yHVNjXhDO0VBBgSULqRawWejNlvlubD0As9ea24CCgNYsiG9Zps7yERN14fL6to1u9pBxDxLyoqeqV2ngj5HTV9FAly6Q2lXUoqXjf+YTjkiFtNLFj6qSbHF2J/aGsuz+Cxn2fMB1Vh1LDTsQGPEaSF2GDg3CXOa9E8PXjRdLC2i0Aub+92yUdnARa54nhZ7nxF9Ly8lfc0STPMN3O7U="


notifications:
   email: 
      - lordrasmus@gmail.com

script:
   - make clean
   - make
   - make -C Samples/Linux/SingleMain/
   - make -C Samples/Linux/SingleMainPython/

#compiler: 
#   - gcc 
#   - clang


addons:
   apt:
      sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.5', 'llvm-toolchain-precise-3.6', 'llvm-toolchain-precise-4.0', 'llvm-toolchain-precise-5.0', 'llvm-toolchain-precise-6.0']
      packages: ['libevent-dev','gcc-4.4','gcc-4.6','gcc-4.7', 'clang-3.5', 'clang-3.6', 'clang-4.0', 'clang-5.0', 'clang-6.0'] # ,'gcc-4.5'
         
matrix:
   include:

   ########################################################################################## 
   #     Windows Test ( basiert auf mingw gcc )                                             #
   ##########################################################################################
   
    # - os: windows
      # install: choco install mingw
      # script: 
        # - mingw32-make clean
        # - mingw32-make

   ##########################################################################################
   #     OSX Test                                                                           #
   ##########################################################################################
   
    # - os: osx
      # osx_image: xcode10
      # compiler: clang
      # env: COMPILER=clang CC=clang
      
      
   ##########################################################################################
   #     Linux Test ( Coveriry )                                                            #
   ##########################################################################################

   # - os: linux
      # compiler: gcc
      # env: COMPILER=gcc CC=gcc
      # addons:
        # apt:
            # packages: ['libevent-dev']
            
        # coverity_scan:
            # project:
                # name: lordrasmus/libcwebui

            # notification_email: 
                # - lordrasmus@gmail.com

            # build_command: make -C lib rebuild
            # branch_pattern: master

   ##########################################################################################
   #     Linux Test                                                                         #
   ##########################################################################################

   
   - os: linux
     env: COMPILER=gcc-4.4 CC=gcc-4.4
    
#   - os: linux
#     env: COMPILER=gcc-4.5 CC=gcc-4.5

   - os: linux
     env: COMPILER=gcc-4.6 CC=gcc-4.6

   - os: linux
     env: COMPILER=gcc-4.7 CC=gcc-4.7     
    
#    - os: linux
#      compiler: gcc-4.6
#      addons:
#        apt:
#          sources: ['ubuntu-toolchain-r-test']
#          packages: ['libevent-dev', 'gcc-4.6']
#      env: COMPILER=gcc-4.6 CC=gcc-4.6
#    - os: linux
#      compiler: gcc-4.7
#      addons:
#        apt:
#          sources: ['ubuntu-toolchain-r-test']
#          packages: ['libevent-dev', 'gcc-4.7']
#      env: COMPILER=gcc-4.7 CC=gcc-4.7
#      
#    - os: linux
#      compiler: gcc-4.8
#      addons:
#        apt:
#          sources: ['ubuntu-toolchain-r-test']
#          packages: ['libevent-dev', 'gcc-4.8']
#      env: COMPILER=gcc-4.8 CC=gcc-4.8

#    - os: linux
#      compiler: gcc-4.9
#      addons:
#        apt:
#          sources: ['ubuntu-toolchain-r-test']
#          packages: ['libevent-dev', 'gcc-4.9']
#      env: COMPILER=gcc-4.9 CC=gcc-4.9

    # - os: linux
      # compiler: gcc-5
      # addons:
        # apt:
          # sources: ['ubuntu-toolchain-r-test']
          # packages: ['libevent-dev', 'gcc-5']
      # env: COMPILER=gcc-5 CC=gcc-5

    # - os: linux
      # compiler: gcc-6
      # addons:
        # apt:
          # sources: ['ubuntu-toolchain-r-test']
          # packages: ['libevent-dev', 'gcc-6']
      # env: COMPILER=gcc-6  CC=gcc-6
    
    # - os: linux
      # compiler: gcc-7
      # addons:
        # apt:
          # sources: ['ubuntu-toolchain-r-test']
          # packages: ['libevent-dev', 'gcc-7']
      # env: COMPILER=gcc-7  CC=gcc-7
     
    # - os: linux
      # compiler: gcc-8
      # addons:
        # apt:
          # sources: ['ubuntu-toolchain-r-test']
          # packages: ['libevent-dev', 'gcc-8']
      # env: COMPILER=gcc-8  CC=gcc-8

    # - os: linux
      # compiler: clang
      # addons:
        # apt:
          # sources: ['ubuntu-toolchain-r-test']
          # packages: ['libevent-dev', 'clang']
      # env: COMPILER=clang CC=clang

    # - os: linux
      # compiler: clang-3.5
      # addons:
        # apt:
          # sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.5']
          # packages: ['libevent-dev', 'clang-3.5']
      # env: COMPILER=clang-3.5  CC=clang-3.5

#    - os: linux
#      compiler: clang-3.6
#      addons:
#        apt:
#          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.6']
#          packages: ['libevent-dev', 'clang-3.6']
#      env: COMPILER=clang-3.6 CC=clang-3.6
      
#    - os: linux
#      compiler: clang-3.7
#      addons:
#        apt:
#          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7']
#          packages: ['libevent-dev', 'clang-3.7']
#      env: COMPILER=clang-3.7 CC=clang-3.7
      
#    - os: linux
#      compiler: clang-3.8
#      addons:
#        apt:
#          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.8']
#          packages: ['libevent-dev', 'clang-3.8']
#      env: COMPILER=clang-3.8 CC=clang-3.8
      
#    - os: linux
#      compiler: clang-3.9
#      addons:
#        apt:
#          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.9']
#          packages: ['libevent-dev', 'clang-3.9']
#      env: COMPILER=clang-3.9 CC=clang-3.9
         
    # - os: linux
      # dist: trusty
      # compiler: clang-4.0
      # addons:
        # apt:
          # sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-4.0']
          # packages: ['libevent-dev', 'clang-4.0']
      # env: COMPILER=clang-4.0 CC=clang-4.0
    
    # - os: linux
      # dist: trusty
      # compiler: clang-5.0
      # addons:
        # apt:
          # sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-5.0']
          # packages: ['libevent-dev', 'clang-5.0']
      # env: COMPILER=clang-5.0 CC=clang-5.0
    
    # - os: linux
      # dist: trusty
      # compiler: clang-6.0
      # addons:
        # apt:
          # sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-6.0']
          # packages: ['libevent-dev', 'clang-6.0']
      # env: COMPILER=clang-6.0 CC=clang-6.0
    


