language: c

env:
  global:
    secure: "SS5efj7kz0thoFmWqwrLwvXVvMMviJ2tKk+y0E6FyiVXZ173qRPn5ZGlIpLVVwx0pev1tf92+RQ/BmTha3lREf+qc9Gt9G3lBXzch4m5+gKAOG2XWvqSKnD2nVGBVjZvvC579Bt1JhFJ1bKMETGdJGOOCNU2+1TQlCfFhOPMCuORBD5m1N2kDWhGoDr8jhoV884gFeLYvSoQLbrXLo9IXVsj+KWI97Ck8SMCtT3oPc7jtqQrsZ4ECS5N+wXvR71HPpgP1lIe/K/wvvkLQmZvVWnVsroiiwGQbWKJuN0CcbG2ooxkzYT4BMbCoVdyezxFZNkyMQB7Adzgera+Cymh0zmQadK4SYuPR6wl+K9K8wgfGDikAw0dUyVnI2JjDvGjRq9IFy8nUfOK70OSP2OLG0FsSLCYENkm5+/iek41gEd7W0A7Kfz6n+4djGguqML8TJaKMY2qQ2so/hyE1Pv2ne2yHVNjXhDO0VBBgSULqRawWejNlvlubD0As9ea24CCgNYsiG9Zps7yERN14fL6to1u9pBxDxLyoqeqV2ngj5HTV9FAly6Q2lXUoqXjf+YTjkiFtNLFj6qSbHF2J/aGsuz+Cxn2fMB1Vh1LDTsQGPEaSF2GDg3CXOa9E8PXjRdLC2i0Aub+92yUdnARa54nhZ7nxF9Ly8lfc0STPMN3O7U="


notifications:
   email: 
      - lordrasmus@gmail.com

script:
   - cat ${TRAVIS_ROOT}/etc/apt/sources.list
#   - echo $CC
#   - echo $CXX
#   - echo ${CC}
#   - echo ${CXX}
   - sudo apt-get install ${CC} ${CXX}
   - make clean
   - make
   - make -C Samples/Linux/SingleMain/
   - make -C Samples/Linux/SingleMainPython/


before_script:
  - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
  - echo "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-3.8 main" | sudo tee -a /etc/apt/sources.list
  - echo "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-3.9 main" | sudo tee -a /etc/apt/sources.list
  - echo "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-4.0 main" | sudo tee -a /etc/apt/sources.list
  - echo "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-5.0 main" | sudo tee -a /etc/apt/sources.list
  - echo "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-6.0 main" | sudo tee -a /etc/apt/sources.list
  - echo "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-7 main" | sudo tee -a /etc/apt/sources.list
  - echo "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-8 main" | sudo tee -a /etc/apt/sources.list
  - echo "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main" | sudo tee -a /etc/apt/sources.list
  - echo "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
#  - sudo apt-get install clang-3.8 clang++-3.8 clang-3.9 clang++-3.9 clang-4.0 clang++-4.0 clang-5.0 clang++-5.0 clang-6.0 clang++-6.0 clang-7 clang++-7 clang-8 clang++-8 clang-9 clang++-9 clang-10 clang++-10
#  - sudo apt-get install clang-3.8 clang-3.9 clang-4.0 clang-5.0 clang-6.0 clang-7 clang-8 clang-9 clang-10
  
  
compiler: gcc 

#dist: bionic
dist: xenial

addons:
   apt:
      sources: # ['ubuntu-toolchain-r-test'] #, 'llvm-toolchain-xenial']
         - sourceline: "ppa:ubuntu-toolchain-r/test"
#         - sourceline: "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-7 main"
      packages: ['libevent-dev'] # , 'gcc-4.4', 'g++-4.4', 'gcc-4.6', 'g++-4.6', 'gcc-4.7', 'g++-4.7', 'gcc-4.8', 'g++-4.8', 'gcc-4.9', 'g++-4.9', 'gcc-5', 'g++-5', 'gcc-6', 'g++-6', 'gcc-7', 'g++-7', 'gcc-8', 'g++-8', 'gcc-9', 'g++-9'] 

stage: test
        
jobs:
   include:

   ########################################################################################## 
   #     Windows Test ( basiert auf mingw gcc )                                             #
   ##########################################################################################
   
    # - os: windows
      # install: choco install mingw
      # script: 
        # - mingw32-make clean
        # - mingw32-make

   ##########################################################################################
   #     OSX Test                                                                           #
   ##########################################################################################
   
    # - os: osx
      # osx_image: xcode10
      # compiler: clang
      # env: COMPILER=clang CC=clang
      
      
   ##########################################################################################
   #     Linux Test ( Coveriry )                                                            #
   ##########################################################################################

   # - os: linux
      # compiler: gcc
      # env: COMPILER=gcc CC=gcc
      # addons:
        # apt:
            # packages: ['libevent-dev']
            
        # coverity_scan:
            # project:
                # name: lordrasmus/libcwebui

            # notification_email: 
                # - lordrasmus@gmail.com

            # build_command: make -C lib rebuild
            # branch_pattern: master

   ##########################################################################################
   #     Linux Test                                                                         #
   ##########################################################################################

   
   - os: linux
     env: COMPILER=gcc-4.4 CC=gcc-4.4 CXX=g++-4.4
    
#   - os: linux
#     env: COMPILER=gcc-4.5 CC=gcc-4.5 CXX=g++-4.5

   # - os: linux
     # env: COMPILER=gcc-4.6 CC=gcc-4.6 CXX=g++-4.6

   # - os: linux
     # env: COMPILER=gcc-4.7 CC=gcc-4.7 CXX=g++-4.7

   # - os: linux
     # env: COMPILER=gcc-4.8 CC=gcc-4.8 CXX=g++-4.8  

   # - os: linux
     # env: COMPILER=gcc-4.9 CC=gcc-4.9 CXX=g++-4.9

   # - os: linux
     # env: COMPILER=gcc-5 CC=gcc-5 CXX=g++-5

   # - os: linux
     # env: COMPILER=gcc-6 CC=gcc-6 CXX=g++-6

   # - os: linux
     # env: COMPILER=gcc-7 CC=gcc-7 CXX=g++-7

   # - os: linux
     # env: COMPILER=gcc-8 CC=gcc-8 CXX=g++-8

   # - os: linux
     # env: COMPILER=gcc-9 CC=gcc-9 CXX=g++-9

   - os: linux
     compiler: clang
     env: COMPILER=clang-3.5  CC=clang-3.5 CXX=clang++-3.5

   - os: linux
     compiler: clang
     env: COMPILER=clang-3.6  CC=clang-3.6 CXX=clang++-3.6

   - os: linux
     compiler: clang
     env: COMPILER=clang-3.7  CC=clang-3.7 CXX=clang++-3.7

   # - os: linux
     # compiler: clang
     # env: COMPILER=clang-3.8  CC=clang-3.8 CXX=clang++-3.8

   # - os: linux
     # compiler: clang
     # env: COMPILER=clang-3.9  CC=clang-3.9 CXX=clang++-3.9

   - os: linux
     compiler: clang
     env: COMPILER=clang-4  CC=clang-4 CXX=clang++-4

   - os: linux
     compiler: clang
     env: COMPILER=clang-5  CC=clang-5 CXX=clang++-5

   - os: linux
     compiler: clang
     env: COMPILER=clang-6  CC=clang-6 CXX=clang++-6     

   # - os: linux
     # compiler: clang
     # env: COMPILER=clang-7  CC=clang-7 CXX=clang++-7

   # - os: linux
     # compiler: clang
     # env: COMPILER=clang-8  CC=clang-8 CXX=clang++-8

   # - os: linux
     # compiler: clang
     # env: COMPILER=clang-9  CC=clang-9 CXX=clang++-9

   # - os: linux
     # compiler: clang
     # env: COMPILER=clang-10  CC=clang-10 CXX=clang++-10
     

    


