language: c

env:
  global:
    - secure: "n9k-QcE9YVc69rhfAkR1uw"

notifications:
   email: 
      - lordrasmus@gmail.com

script:  make -C lib

compiler:
  - clang
  - gcc

addons:
  coverity_scan:
     notification_email: scan_notifications@example.com
     build_command: make -C lib
