# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo "Hello World! $(gcc -v)"
  displayName: 'Run a one-line script'

- script: |
    sudo apt -y install python-dev-is-python3 libevent-dev
    make
  displayName: 'Run a multi-line script'
