SHELL=/bin/bash

STD_FLAGS= -Wno-conversion # -fsanitize=address

EXTRA_INCLUDE= -I. -Iinclude -Iplatform/include -Ithird_party/src/rb_tree -Ithird_party/src/simclist
#EXTRA_INCLUDE+=-fvisibility=hidden
EXTRA_INCLUDE+=-DLINUX -D__USE_POSIX

STD_LIBS= -levent -levent_pthreads -lssl -pthread -lcrypto -lUtils
LIB_NAME= libWebserver.so

include Makefile.files
HEADER := 	include/webserver_api_functions.h include/webserver_api_functions_macros.h WebserverConfig.h third_party/src/simclist/simclist.h

header_install:
	$(call COPY_HEADER,"Webserver")

build:
	$(call PRINT_PLUGIN,"Building Webserver Lib")
	@$(MAKE) -f Makefile.bbs --no-print-directory build_objs

clean: clean_build


include $(PLUGIN_MAKEFILES)/shared_lib.include



