

MBEDTLS := 	third_party/src/mbedtls-2.4.2/library/ssl_cookie.c \
			third_party/src/mbedtls-2.4.2/library/md.c \
			third_party/src/mbedtls-2.4.2/library/md_wrap.c \
			third_party/src/mbedtls-2.4.2/library/ssl_tls.c \
			third_party/src/mbedtls-2.4.2/library/entropy.c \
			third_party/src/mbedtls-2.4.2/library/entropy_poll.c \
			third_party/src/mbedtls-2.4.2/library/pk.c \
			third_party/src/mbedtls-2.4.2/library/x509.c \
			third_party/src/mbedtls-2.4.2/library/x509_crt.c \
			third_party/src/mbedtls-2.4.2/library/sha512.c \
			third_party/src/mbedtls-2.4.2/library/ctr_drbg.c \
			third_party/src/mbedtls-2.4.2/library/timing.c \
			third_party/src/mbedtls-2.4.2/library/certs.c \
			third_party/src/mbedtls-2.4.2/library/asn1write.c \
			third_party/src/mbedtls-2.4.2/library/asn1parse.c \
			third_party/src/mbedtls-2.4.2/library/oid.c \
			third_party/src/mbedtls-2.4.2/library/pem.c \
			third_party/src/mbedtls-2.4.2/library/base64.c \
			third_party/src/mbedtls-2.4.2/library/md5.c \
			third_party/src/mbedtls-2.4.2/library/des.c \
			third_party/src/mbedtls-2.4.2/library/aes.c \
			third_party/src/mbedtls-2.4.2/library/aesni.c \
			third_party/src/mbedtls-2.4.2/library/pkparse.c \
			third_party/src/mbedtls-2.4.2/library/pk_wrap.c \
			third_party/src/mbedtls-2.4.2/library/ecp.c \
			third_party/src/mbedtls-2.4.2/library/ecp_curves.c \
			third_party/src/mbedtls-2.4.2/library/bignum.c \
			third_party/src/mbedtls-2.4.2/library/rsa.c \
			third_party/src/mbedtls-2.4.2/library/ripemd160.c \
			third_party/src/mbedtls-2.4.2/library/sha1.c \
			third_party/src/mbedtls-2.4.2/library/sha256.c \
			third_party/src/mbedtls-2.4.2/library/pkcs5.c \
			third_party/src/mbedtls-2.4.2/library/pkcs12.c \
			third_party/src/mbedtls-2.4.2/library/cipher.c \
			third_party/src/mbedtls-2.4.2/library/arc4.c \
			third_party/src/mbedtls-2.4.2/library/gcm.c \
			third_party/src/mbedtls-2.4.2/library/ecdsa.c \
			third_party/src/mbedtls-2.4.2/library/hmac_drbg.c \
			third_party/src/mbedtls-2.4.2/library/cipher_wrap.c \
			third_party/src/mbedtls-2.4.2/library/blowfish.c \
			third_party/src/mbedtls-2.4.2/library/ccm.c \
			third_party/src/mbedtls-2.4.2/library/camellia.c \
			third_party/src/mbedtls-2.4.2/library/ssl_ciphersuites.c \
			third_party/src/mbedtls-2.4.2/library/ecdh.c \
			third_party/src/mbedtls-2.4.2/library/dhm.c \
			third_party/src/mbedtls-2.4.2/library/ssl_srv.c \
			third_party/src/mbedtls-2.4.2/library/debug.c \
			third_party/src/mbedtls-2.4.2/library/net_sockets.c \
			third_party/src/mbedtls-2.4.2/library/ssl_tls.c \
			third_party/src/mbedtls-2.4.2/library/ssl_cli.c

SOURCES := 	src/builtinFunctions.c \
			src/cookie.c src/convert.c \
			src/conditions.c src/engine.c \
			src/engine_parser.c \
			src/engine_functions.c \
			src/engine_api_extensions.c \
			src/engine_if.c \
			src/engine_tags.c \
			src/file_manager.c \
			src/globals.c \
			src/header.c \
			src/header_parser.c \
			src/header_send.c \
			src/linked_list.c \
			src/message_queue.c \
			src/server.c \
			src/server_chunk_functions.c \
			src/server_config.c \
			src/server_error_pages.c \
			src/session.c \
			src/system.c \
			src/system_memory.c \
			src/system_sockets.c \
			src/system_sockets_recv.c \
			src/system_sockets_send.c \
			src/system_sockets_container.c \
			src/system_sockets_events.c \
			src/system_sockets_select.c \
			src/system_file_access.c \
			src/system_file_access_utils.c \
			src/system_file_access_fs.c \
			src/system_file_access_binary.c \
			src/system_file_access_wnfs.c \
			src/system_file_cache.c \
			src/webserver_api_functions.c \
			src/utils.c \
			src/log.c \
			src/variable.c \
			src/variable_global.c \
			src/variable_store.c \
			src/variable_render.c \
			src/websockets.c \
			src/websockets_send_recv.c \
			src/websocket_handler.c \
			ssl/openssl.c \
			ssl/mbedtls.c \
			python/py_utils.c \
			python/py_plugin.c \
			python/py_api_functions.c \
			platform/linux/platform-file-access.c \
			platform/linux/platform-sockets.c \
			platform/linux/system-unix.c \
			third_party/src/rb_tree/red_black_tree.c third_party/src/rb_tree/misc.c third_party/src/rb_tree/stack.c \
			third_party/src/is_utf8/is_utf8.c \
			third_party/src/miniz/miniz_tdef.c third_party/src/miniz/miniz_tinfl.c third_party/src/miniz/miniz.c \

#			$(MBEDTLS)



