# Your .github/workflows/coverity.yml file.
name: Coverity Scan

# We only want to test official release code, not every pull request.
on:
  push:
    branches: [master]

jobs:
  coverity:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v2
    - name: Install dev packagea
      run: sudo apt-get install -y libevent-dev python-dev
  
    - uses: vapier/coverity-scan-action@v1
      with:
        email: ${{ secrets.COVERITY_SCAN_EMAIL }}
        token: ${{ secrets.COVERITY_SCAN_TOKEN }}
    
